# Generated by Django 3.0.14 on 2026-04-14 13:59

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0009_auto_20200611_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='backlinks',
            field=jsonfield.fields.JSONField(blank=True, default=list, verbose_name='backlinks'),
        ),
    ]
