# Generated by Django 3.0.14 on 2026-04-14 14:04

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.search
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=255)),
                ('fcm_token', models.TextField(unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=200)),
                ('device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('app_version', models.CharField(blank=True, max_length=500, null=True)),
                ('os_version', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'FCM Token',
                'db_table': 'mobile_fcm_tokens',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GeoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('form_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Form data from survey')),
                ('points', django.contrib.postgres.fields.jsonb.JSONField(default=list, help_text='Array of {latitude, longitude, timestamp, ...}')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('geom_3857', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=3857)),
                ('search_text', models.TextField(blank=True, default='')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
            ],
            options={
                'db_table': 'geoform_geodata',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileAppVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Semantic version (e.g., 1.0.0)', max_length=20, unique=True)),
                ('version_code', models.IntegerField(help_text='Integer version code for comparison', unique=True)),
                ('apk_url', models.URLField(help_text='URL to download the APK file', max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('checksum', models.CharField(blank=True, help_text='MD5 or SHA256 checksum', max_length=64, null=True)),
                ('release_notes', models.TextField(blank=True, help_text="What's new in this version")),
                ('is_mandatory', models.BooleanField(default=False, help_text='Force users to update')),
                ('is_active', models.BooleanField(default=True, help_text='Available for download')),
                ('released_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mobile App Version',
                'db_table': 'mobile_app_versions',
                'ordering': ['-version_code', '-released_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='mobile_notifications/')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mobile_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('geometry_type', models.CharField(choices=[('point', 'Point'), ('line', 'Line'), ('polygon', 'Polygon')], max_length=20)),
                ('form_fields', django.contrib.postgres.fields.jsonb.JSONField(default=list, help_text='List of form field definitions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'geoform_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry_type', models.CharField(choices=[('point', 'Point'), ('line', 'Line'), ('polygon', 'Polygon')], default='point', max_length=20)),
                ('json_template', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='JSON template for form validation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'geoform_project_groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('project_upload', 'Project Upload'), ('project_download', 'Project Download'), ('geodata_upload', 'GeoData Upload'), ('geodata_download', 'GeoData Download'), ('geodata_delete', 'GeoData Delete')], max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], max_length=20)),
                ('project_mobile_id', models.CharField(blank=True, max_length=100, null=True)),
                ('geodata_mobile_id', models.CharField(blank=True, max_length=100, null=True)),
                ('items_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('request_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('device_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'geoform_sync_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TMSLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, default='', max_length=255)),
                ('tms_url', models.CharField(max_length=500)),
                ('base_url', models.CharField(default='https://portal-gis.tap-agri.com', max_length=500)),
                ('min_zoom', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('max_zoom', models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TMS Layer',
                'db_table': 'mobile_tms_layers',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='tmslayer',
            index=models.Index(fields=['code'], name='mobile_tms__code_62bad9_idx'),
        ),
        migrations.AddIndex(
            model_name='tmslayer',
            index=models.Index(fields=['is_active', 'code'], name='mobile_tms__is_acti_b66485_idx'),
        ),
        migrations.AddField(
            model_name='synclog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='access_by',
            field=models.ManyToManyField(blank=True, help_text='Users with access to this group', related_name='mobile_accessed_project_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_created_project_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectgroup',
            name='projects',
            field=models.ManyToManyField(blank=True, help_text='Projects in this group', related_name='groups', to='mobileadmin.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='collectors',
            field=models.ManyToManyField(blank=True, help_text='Users who collect data for this project', related_name='mobile_collected_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_created_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mobilenotification',
            name='receivers',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='mobileadmin.FCMToken'),
        ),
        migrations.AddField(
            model_name='mobileappversion',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_released_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='geodata',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_collected_geodata', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='geodata',
            name='project',
            field=models.ForeignKey(db_column='project_mobile_id', on_delete=django.db.models.deletion.CASCADE, related_name='geo_data', to='mobileadmin.Project', to_field='mobile_id'),
        ),
        migrations.AddField(
            model_name='fcmtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_fcm_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['user', 'created_at'], name='geoform_syn_user_id_1d011a_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['sync_type', 'status'], name='geoform_syn_sync_ty_1b92d0_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['project_mobile_id'], name='geoform_syn_project_b239bb_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['geodata_mobile_id'], name='geoform_syn_geodata_e280f6_idx'),
        ),
        migrations.AddIndex(
            model_name='projectgroup',
            index=models.Index(fields=['name'], name='geoform_pro_name_13fede_idx'),
        ),
        migrations.AddIndex(
            model_name='projectgroup',
            index=models.Index(fields=['created_by'], name='geoform_pro_created_62c170_idx'),
        ),
        migrations.AddIndex(
            model_name='projectgroup',
            index=models.Index(fields=['is_active', 'is_deleted'], name='geoform_pro_is_acti_9161e9_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['mobile_id'], name='geoform_pro_mobile__7d2653_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='geoform_pro_created_15c009_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_active', 'is_deleted'], name='geoform_pro_is_acti_6099f4_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileappversion',
            index=models.Index(fields=['version_code'], name='mobile_app__version_e585eb_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileappversion',
            index=models.Index(fields=['is_active'], name='mobile_app__is_acti_186202_idx'),
        ),
        migrations.AddIndex(
            model_name='mobileappversion',
            index=models.Index(fields=['-version_code', 'is_active'], name='mobile_app__version_418916_idx'),
        ),
        migrations.AddIndex(
            model_name='geodata',
            index=models.Index(fields=['mobile_id'], name='geoform_geo_mobile__f2f6ac_idx'),
        ),
        migrations.AddIndex(
            model_name='geodata',
            index=models.Index(fields=['project', 'created_at'], name='geoform_geo_project_dd3fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='geodata',
            index=models.Index(fields=['collected_by'], name='geoform_geo_collect_308c19_idx'),
        ),
        migrations.AddIndex(
            model_name='geodata',
            index=models.Index(fields=['is_deleted'], name='geoform_geo_is_dele_45b86d_idx'),
        ),
        migrations.AddIndex(
            model_name='fcmtoken',
            index=models.Index(fields=['user', 'is_active'], name='mobile_fcm__user_id_c78c30_idx'),
        ),
        migrations.AddIndex(
            model_name='fcmtoken',
            index=models.Index(fields=['device_id', 'user'], name='mobile_fcm__device__3afef2_idx'),
        ),
        migrations.AddIndex(
            model_name='fcmtoken',
            index=models.Index(fields=['is_active', 'updated_at'], name='mobile_fcm__is_acti_e64a73_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fcmtoken',
            unique_together={('user', 'device_id')},
        ),
    ]
