# Generated by Django 3.0.14 on 2026-04-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='Terestria Mobile Admin', max_length=255)),
                ('logo_url', models.URLField(blank=True, default='', max_length=500)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='admin_settings/')),
                ('primary_color', models.CharField(default='#388e3c', help_text='Hex color code', max_length=7)),
                ('primary_dark', models.CharField(default='#2e7d32', max_length=7)),
                ('primary_light', models.CharField(default='#66bb6a', max_length=7)),
                ('sidebar_color', models.CharField(default='#1b5e20', max_length=7)),
                ('accent_color', models.CharField(default='#4caf50', max_length=7)),
                ('background_color', models.CharField(default='#f6faf6', max_length=7)),
                ('font_family', models.CharField(default='Plus Jakarta Sans', max_length=255)),
                ('default_map_center_lng', models.FloatField(default=110.5)),
                ('default_map_center_lat', models.FloatField(default=-2.5)),
                ('default_map_zoom', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Admin Settings',
                'verbose_name_plural': 'Admin Settings',
                'db_table': 'mobile_admin_settings',
            },
        ),
    ]
